version: '3.8'

services:
 
  flask-app:
    build:
      context: .
    image: flask-app
    container_name: "flask-greet"
    ports:
      - "80:80"
    command: python run.py 
    restart: always
    
